articles/urls.py
from django.urls import path 
from . import views 

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    
    path('<int:id>/', views.detail, name='detail'),
    
    path('create/', views.create, name ='create'),

    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),

    path('<int:article_id>/comments/delete/<int:id>/', views.delete_comment, name='delete_comment'),
]

board_test/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('articles/', include('articles.urls')), 
]

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):          # 게시판 
    title = models.CharField(max_length=50)  # 제목 
    content = models.TextField()            # 내용 


class Comment(models.Model):       # 댓글 
    content = models.TextField()    # 작성칸 
    article = models.ForeignKey(Article,on_delete=models.CASCADE) # 

articles/forms.py
from django import forms
from .models import Article
from .models import Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model=Article
        fields='__all__'

class CommentForm(forms.ModelForm):
    
    class Meta:
        model=Comment
        fields=('content',) #튜플형태로
    

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm


# Create your views here.

def index(request): 
    articles = Article.objects.all()

    context = {
        'articles' : articles, 
    }

    return render(request, 'index.html', context)

def detail(request, id):
    article = Article.objects.get(id=id)
    comment_form = CommentForm()


    context = {
        'article': article, 
        'comment_form': comment_form,
    }
    return render(request,'detail.html', context)


def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        context={
            'form':form
        }
        if form.is_valid():
            article=form.save()
            return redirect('articles:index')
            
    else:
        form = ArticleForm()
    context={
        'form':form
    }
    return render(request, 'create.html', context)

def comment_create(request,article_id):
    comment_form = CommentForm(request.POST) # comment_form 변수에 CommentForm 클래스로 받은 댓글 content를 받은 것을 저장
    if comment_form.is_valid():
        comment=comment_form.save(commit=False) # DB에 저장하기 전에 잠깐 멈춰! 
        article=Article.objects.get(id=article_id)
        comment.article=article
        comment.save()
        
        return redirect('articles:detail', id=article_id)

def delete_comment(request, article_id, id):
    comment = Comment.objects.get(id=id)
    comment.delete()

    return redirect('articles:detail', id=article_id)
    
    
    
    
    

    

articles/templates/create.html
{%extends 'base.html'%}
{% block body%}

    <form action="" method="POST">
        {%csrf_token%}
        <p>{{form}}</p>


        <input type="submit">
    </form>

{% endblock%}

articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}

    <h1>{{article.title}}</h1>
    <h3>{{article.content}}</h3>
    <hr>
    <form action="{% url 'articles:comment_create' article_id=article.id%}" method="POST">
        {%csrf_token%}
        {{comment_form}}

        <input type="submit">

    </form>
    {%if not article.comment_set.all|length %}
        <p>댓글이 없습니다.</p>
    {%endif%}
    

    {%for comment in article.comment_set.all %}
        <p>{{comment.content}}</p>
        <a href="{% url 'articles:delete_comment' article_id=article.id id=comment.id%}">X</a>
    {%endfor%}

{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}

    {% for article in articles %}
        <p>{{article.title}} 
            <a href="{% url 'articles:detail' id=article.id %}">detail</a>
        </p>
        
        <hr>
    {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{%url 'articles:index' %}">Home</a>
    <a href="{%url 'articles:create' %}">Create</a>
    {% block body %}      
        
    {% endblock %}    
</body>
</html>